### ISSUE TITLE
`argparse` should probably not be specified in `setup.cfg`

### ISSUE THREAD

**Issue by Fuuzetsu** [decompals/n64img#10]
AFAIU it's a stdlib package so it shouldn't go in here. It should just be left out I think. Please correct me if I'm mistaken.

----

My _specific_ use-case is that I have some tool (not pip) that verifies against the wheel file and it's complaining about argparse not being present because _I think_ it only checks against third-party libraries, which argparse isn't part of. Shame on the tool of course but if it can be addressed here, that's nice too!

**Comment by ethteck** [comment]
Thanks for the report - yeah, looks like argparse used to be a separate package but has long since been part of the standard library. Whoopz. https://github.com/decompals/n64img/releases/tag/0.3.1 hopefully addresses this. Let me know?

**Comment by Fuuzetsu** [comment]
That works great, thank you for very quick action! I was going to comment straight away but GitHub was having problems last night...

**Comment by ethteck** [comment]
Np. Thanks to you as well!
